name: Deploy Public S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: "S3 Bucket Name"
        required: true
      aws_access_key:
        description: "AWS Access Key ID"
        required: true
      aws_secret_key:
        description: "AWS Secret Access Key"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.aws_secret_key }}
        run: |
          terraform plan -var="bucket_name=${{ github.event.inputs.bucket_name }}"

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.aws_secret_key }}
        run: |
          terraform apply -auto-approve -var="bucket_name=${{ github.event.inputs.bucket_name }}"

